### ISSUE TITLE
Información adicional de los votantes

### ISSUE THREAD

**Issue by danieldml112** [mansancab3/decide-io-auth#4]
**¿Está tu petición de mejora relacionada con un problema? Por favor, descríbelo**
No.

**Describe la solución que te gustaría que se implementase**
Para el módulo de Almacenamiento, queremos mostrar estadísticas de las votaciones, teniendo información adicional de los votantes para clasificarlos (siempre con anonimato):
* Sexo: Hombre o mujer.
* Edad: Fecha de nacimiento.
* Lugar: un lugar distintivo (ciudad, país; libre configuración)

**Describe posibles alternativas que hayas considerado**
Nuevos campos que completen esta información en el modelo de la base de datos.

**Contenido adicional**
Nada.

**Comment by walviealv** [comment]
Necesitaríamos el campo 'dateUsuario' como DateField, para facilitar las estadísticas asociadas a el y garantizar la integridad de los datos como fecha y evitar validaciones sobre una cadena. 

Además, habéis creado un modelo nuevo 'Usuario'. Se debería extender al 'User' de django, en caso contrarío el funcionamiento sería incorrecto ya que ese 'Usuario' no tendría el 'voting_id' correspondiente para establecer su relación con el censo. 

Gracias.

**Comment by juanmiguelruiz** [comment]
Con el fin de no discriminar al colectivo LGTBI, el campo **Sex** de registro de usuario propongo añadir la opción "Other".
