### ISSUE TITLE
Integración con GitHub

### ISSUE THREAD

**Issue by mansancab3** [mansancab3/decide-io-auth#7]
Petición de mejora:

Quiero tener la posibilidad de loguearme de una forma rápida y sencilla

Descripción de solución a implementar:

Integración de GitHub como método para loguearse

**Comment by juanmiguelruiz** [comment]
Problemas de integración con social-auth-app-django, no redirige las urls.

**Comment by mansancab3** [comment]
Tras multiples intentos fallidos se optará por la integración de otras redes sociales.
