### ISSUE TITLE
Implementar CSS y Bootstrap

### ISSUE THREAD

**Issue by mansancab3** [mansancab3/decide-io-auth#9]
*Describe la solución que te gustaría que se implementase*
Con el fin de mejorar la experiencia de usuario, se deben crear la pagina de index, log in y sign in. 

*Describe posibles alternativas que hayas considerado*
Desarrollo de código HTML5, usando hojas de estilo CSS3 y Bootstrap.

**Comment by juanmiguelruiz** [comment]
Segundo commit de igual nombre al solucionar conflictos ocasionados al hacer un merge.

**Comment by juanmiguelruiz** [comment]
commit 5c816723a858d029d172f881fdda24bf8b2136ef

**Comment by mansancab3** [comment]
Footer da fallo en pantalla de baja resolución

**Comment by juanmiguelruiz** [comment]
commit 68037232ae6a934a74c84a1c0f6b1649243c9910
